### ISSUE TITLE
1.0 Launch Checklist

### ISSUE THREAD

**Issue by jfrolich** [reasonml-community/graphql-ppx#153]
🚀 Launch checklist 🚀:
- [x] Fix template tag
- [x] Annotate query options using decorators instead of a dangling record
- [x] Extension for inline queries
- [x] contribute compatible version of `reason-apollo-hooks` (in progress: https://github.com/reasonml-community/reason-apollo-hooks/pull/117)
- [ ] contribute compatible version of `reason-urql`
- [x] contribute compatible version of `@jfrolich/reason-gatsby`
- Critical documentation
  - [x] README.md
  - [x] API docs 
  - [x] getting started
  - [x] installation

**Comment by BlueHotDog** [comment]
Hey, i soooo want to try the v1 but am using urql, is there a timeline to have it added?

**Comment by jfrolich** [comment]
1.0 is stable URQL “just” needs to upgrade. I am not sure how easy this is but happy to assist.

**Comment by jfrolich** [comment]
See: https://github.com/FormidableLabs/reason-urql/issues/219
